export const inverDetails = [
  {
    id: "R14",
    username: "Johnson Buyan",
    client: "Client SS 2A521",
    "Inverter Telemetry": "ON",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "9:45 PM",
    unread: "",
  },
  {
    id: "R21",
    username: "Jack Grealish",
    client: "Client SS 2E213",
    "Inverter Telemetry": "OFF",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "Yesterday",
    unread: "5",
  },
  {
    id: "R27",
    username: "Micheal CEO",
    client: "Client SS 2D532",
    "Inverter Telemetry": "ON",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "4:05 AM",
    unread: "",
  },
  {
    id: "R16",
    username: "Leo Farenheit",
    client: "Client SS 2B822",
    "Inverter Telemetry": "OFF",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "11:32 PM",
    unread: "2",
  },
  {
    id: "R28",
    username: "Mercy Messi",
    client: "Client SS 2B321",
    "Inverter Telemetry": "ON",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "2:00 PM",
    unread: "3",
  },
  {
    id: "R23",
    username: "Joan Lopetegui",
    client: "Client SS 2E388",
    "Inverter Telemetry": "OFF",
    "Lock System": "Lock",
    message: "Inverter powered off just before the backup generator kicked in.",
    time: "Yesterday",
    unread: "",
  },
];
